# train_config.yml

device: "cuda"

paths:
  data_dir: "/mnt/c/Users/narun/OneDrive/Desktop/Project/MGN_ADM/datasets/hydrogel"
  model_load_dir: null
  rollout_dir: null
  
model:
  latent_size: 128
  timestep: 1e-5
  time_window: 3
  message_passing_steps: 15
  include_push_forward: true
  voxel_size: 0.08


